# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- development
- qa
- demo
- uat
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: |
    yarn install
  displayName: 'yarn install'

- script: |
    npm run build:dev
  displayName: 'build for dev'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/development'))

- script: |
    npm run build:qa
  displayName: 'build for qa'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/qa'))

- script: |
    npm run build:demo
  displayName: 'build for demo'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/demo'))

- script: |
    npm run build:uat
  displayName: 'build for uat'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/uat'))

- script: |
    npm run build:production
  displayName: 'build for production'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))

- task: CopyFiles@2
  inputs:
    SourceFolder: 'build/'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    CleanTargetFolder: true
    OverWrite: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'ReactApp'
    publishLocation: 'Container'